### ISSUE TITLE
Prof Comments

### ISSUE THREAD

**Issue by helloqx** [nus-mtp/cs-modify#26]
Commit message/changelog for modifying modules
Restore module button -> undo icon
Bold important info (module information)
Group changes into sections
Table Old Module and New Module

**Comment by tgqiang** [comment]
> Commit message/changelog for modifying modules
Requires addition of change-log message tracking in backend (Use Case: "User can specify a message explaining/detailing reasons for the change applied to a module")

> Restore module button -> undo icon
Change implemented.

> Bold important info (module information)
Adjusted width of columns displaying module code and name

> Group changes into sections
The UI will depend largely on back-end.

> Table Old Module and New Module
Will be implementing child rows for the table that display changes in module details. UI for displaying other module changes are already revised accordingly.

**Comment by tgqiang** [comment]
UI revisions for specific module modifications currently work-in-progress.

**Comment by tgqiang** [comment]
Update: Modified Modules UI is 80% complete, left with back-end support for displaying modified module details for a target module with respect to issues #43 and #47.

**Comment by tgqiang** [comment]
First point in this issue extracted out to #54 

Others are addressed or already addressed; this issue will be closed with resolution of #43 and #47 .
