### ISSUE TITLE
Implement Frontend for High Level #4

### ISSUE THREAD

**Issue by nlzz22** [nus-mtp/cs-modify#29]
This feature is to show all modules taken prior to an internship in specific AY-Semester.
Currently, /moduleTakenPriorToInternship page is now defaulted to show those modules taken prior to internship in "AY 17/18 Sem 1".
The AY-Sem value is passed in via modules_taken_prior_to_internship.py
Please implement the UI for this feature, thanks.

The files associated are:
components/handlers/modules_taken_prior_to_internship.py
templates/modulesTakenPriorToInternship.html

**Comment by tgqiang** [comment]
Closing this as this is implemented in nus-mtp/cs-modify#34. If this still needs addressing, please do so through the pull request, or reopen this issue.
