### ISSUE TITLE
404 Page Error Message Emphasis

### ISSUE THREAD

**Issue by helloqx** [nus-mtp/cs-modify#33]
Make it more 'popz'
Currently the error message looks like part of the generic instructions, easily overlooked
![image](https://cloud.githubusercontent.com/assets/12347266/23942129/3b3e4940-09a6-11e7-87b0-258e9e69a741.png)

**Comment by tgqiang** [comment]
![image](https://cloud.githubusercontent.com/assets/12386860/24000428/2c83b39a-0a96-11e7-9338-2750cb6cf23a.png)

@helloqx is this better?

**Comment by helloqx** [comment]
👍 Looks great

**Comment by tgqiang** [comment]
Patched in <code>sprintFiveGq</code> branch.
