### ISSUE TITLE
capitalize all module codes for user

### ISSUE THREAD

**Issue by a0129998** [nus-mtp/cs-modify#41]
allow users to input small letters, but capitalize the letters for them with `.upper()`

**Comment by tgqiang** [comment]
This has been fixed for 'Modules Taken Prior to Other Modules' page.

For 'Add Module' page, this was just implemented in [5a98d4c](https://github.com/nus-mtp/cs-modify/commit/5a98d4c066349589dd966e6298e8ff782c54b17d).

This issue will now be closed.
