### ISSUE TITLE
dynamic current sem

### ISSUE THREAD

**Issue by a0129998** [nus-mtp/cs-modify#42]
currently the current sem for `non-overlapping modules by semester` is hardcoded to be `AY 16/17 SEM 1`. modify it to make the time dynamic

**Comment by tgqiang** [comment]
@a0129998 @helloqx @nlzz22 @xaterz remind me to ask Prof. Ooi on whether there are existing NUS APIs that allow us to track the semester that is running, given the current date and time.

**Comment by nlzz22** [comment]
I am currently coding that function in branch classSizeEnhancement. (for issue #57)
