### ISSUE TITLE
Request for UI for preclusion and prereq

### ISSUE THREAD

**Issue by nlzz22** [nus-mtp/cs-modify#46]
module_view_in_ay_sem.py
module_edit.py
module_overview.py
currently has retrieved data from database with regards to preclusions and prereqs,
please help to add them to the RENDER() and do up the UI. Thanks.
They are found in queries2 branch.

**Comment by tgqiang** [comment]
Will work on it. However, please note that this will most likely not be completed in time for this sprint.

**Comment by tgqiang** [comment]
@nlzz22 @a0129998 @xaterz @helloqx 
A draft interface has been written, will demonstrate the interface to all of you on Friday.

**Comment by tgqiang** [comment]
Interface for editing module prerequisites have been implemented.

**Comment by tgqiang** [comment]
All interfaces are implemented and will be submitting a pull request soon.
