### ISSUE TITLE
Logout confirmation pop-up to be implemented

### ISSUE THREAD

**Issue by xaterz** [nus-mtp/cs-modify#51]
Currently, clicking on the logout button will log the user out immediately.

Should have a pop-up confirmation that asks the user "Are you sure you want to log out?" and the user has to press 'OK' to log out.

**Comment by tgqiang** [comment]
Patched in commits [afeb9fa](https://github.com/nus-mtp/cs-modify/commit/afeb9faa1df06d381e3f7a3f022fe4cf0d625bca) and [edd8df5](https://github.com/nus-mtp/cs-modify/commit/edd8df54fcb8131692269ec5684719f87081db51).
