### ISSUE TITLE
No longer able to edit specific modules

### ISSUE THREAD

**Issue by helloqx** [nus-mtp/cs-modify#56]
line 137 of components/handlers/module_edit.py:
`elif quota < 0 or (quota is not None and type(quota) != int):`
Causes all tentative module mountings to fail as:
1) Python evaluates None < 0 == True (fail if mounted -> unmounted)
2) type(quota) = unicode (fail if unmounted -> mounted)

**Comment by tgqiang** [comment]
Patched by @xaterz in his commit, this issue will be closed.
