### ISSUE TITLE
Find Modules with Specified Class Size feature enhancement

### ISSUE THREAD

**Issue by tgqiang** [nus-mtp/cs-modify#57]
A few things to tweak for the search function:
1. Leaving the AY-Semester field blank can invoke search in the current AY-Semester
2. Leaving the left-interval for class size blank should search for all modules with class size <= right-interval
3. Leaving the right-interval for class size blank should search for all modules with class size >= left-interval

**Comment by nlzz22** [comment]
Implementation to be changed to:
1. AY-Semester will default to current AY-Sem upon loading the page initially, subsequently, as before, will default to previous search result.
2. Left and right intervals for class size cannot be left blank, but will be defaulted to the range of 0 to 999
