### ISSUE TITLE
Module listing navigation box too big

### ISSUE THREAD

**Issue by xaterz** [nus-mtp/cs-modify#61]
![image](https://cloud.githubusercontent.com/assets/13976925/24133494/59789352-0e38-11e7-9615-b7d969e7f03d.png)
The box containing the 2 navigation buttons is taking up too much space on this page. You can barely see the table on page load.

**As a general rule of thumb, the header, description and navigation buttons of a page should not take up more than half of the page.**

Suggestions for what to be changed:
* Remove the 'Options' header (the buttons are self-explanatory enough)
* Change the 2 buttons' display to inline-block
* Reduce the top and bottom padding of the box

**Comment by tgqiang** [comment]
Patched in https://github.com/nus-mtp/cs-modify/commit/f0cc9f0e1b10fedfc94fd6e4db4ca848804ff2a2, https://github.com/nus-mtp/cs-modify/commit/989569a6301014990d643584b139fae3bedbb0a9 and https://github.com/nus-mtp/cs-modify/commit/6a9cf08b4572bd0d21731ab9bd9f36bbb1124065.
