### ISSUE TITLE
Implementation of 404 page needs refinement

### ISSUE THREAD

**Issue by xaterz** [nus-mtp/cs-modify#62]
Currently there are 2 problems with handling 404 error:

1) There is no proper redirect to a 404 page. For example in Module Overview, when the module code in the URL is invalid, the 404 page is rendered, but the URL remains the same.
The correct way to do this is to have a general URL for the 404 page (localhost/404), and create a new class to handle the rendering of the 404 page (instead of calling RENDER directly).

2) So far we are only able to catch invalid code and AY-Sems in the GET input of the page, but there's no catching of REAL 404 error. E.g. 'localhost/asdfghjk' will print a 'not found' on the page instead of directing to our customised 404 page.

**Comment by tgqiang** [comment]
Point 1 is not the way to do this.

Will be working to implement refinement for point 2.

**Comment by tgqiang** [comment]
Point 2 patched with https://github.com/nus-mtp/cs-modify/commit/3393fa51b33f216bb99fec8ed9064c627cdc015d
