### ISSUE TITLE
dataTable in Modified Modules is causing javascript error

### ISSUE THREAD

**Issue by xaterz** [nus-mtp/cs-modify#82]
Uncaught TypeError: Cannot set property '_DT_CellIndex' of undefined

This error is preventing javascript codes from being executed on this page.

**Comment by tgqiang** [comment]
Fixed in https://github.com/nus-mtp/cs-modify/commit/929a47cbfc77d16b300ef7ff364f7fefdf9540fa and https://github.com/nus-mtp/cs-modify/commit/153eea2c1260870f26cfbce1355b32a2124ac307
