### ISSUE TITLE
Database unable to handle multiple concurrent requests

### ISSUE THREAD

**Issue by xaterz** [nus-mtp/cs-modify#96]
Load testing using apache benchmark revealed that the postgres database has a very high chance of crashing when more than one requests of the same type are sent concurrently. Meaning if more than one user try to access the same page at the same time, the app might crash.

To prevent this, need to make every database 'get' function able to:
* Catch internal error returned by postgres
* Retry after 1 second when query failed
* Redirect to home page / error page after too many failed attempts

**Comment by nlzz22** [comment]
Closed as of PR #95
